name: Hakyll Blog CI

on:
  push:
    branches: [ hakyll ]
  pull_request:
    branches: [ hakyll ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - uses: actions/setup-haskell@v1
      with:
        stack-version: '2.2'

    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.DEPLOY_PRIVATE_KEY }}"
    
    - name: Update timestamps from git
      run: | 
        git ls-tree -r --name-only HEAD | while read filename; do
          TS="$(git log -1 --format="%ct" -- ${filename})"
          echo $TS
          touch "${filename}" -mt "$(date --date="@$TS" "+%Y%m%d%H%M.%S")"
          echo "touch \"${filename}\" -mt \"$(date --date="@$TS" "+%Y%m%d%H%M.%S")\""
        done
                    
    - name: Cache ~/.stack dependencies
      id: cache-stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: stack-home-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('package.yaml') }}
        restore-keys: |
          stack-home
    
    - name: Cache .stack-work
      id: cache-stack-work
      uses: actions/cache@v1
      with:
        path: .stack-work
        key: stack-work-${{ github.sha }}
        restore-keys: |
          stack-work-${{ github.sha }}
          stack-work
    

    - name: Resolve/Update dependencies
      if: steps.cache-stack-local-bin.outputs.cache-hit != 'true'
      run: |
        stack setup
        stack build --dependencies-only
        
    - name: Build Site
      run: stack build --pedantic
      
    - name: Generate Static Site
      run: stack exec site build
      
    - name: Publish GitHub Pages 
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        git fetch --all --prune --unshallow
        stack exec site build
        git stash
        git checkout master
        cp -a _site/* .
        git config --global user.email "actions@github"
        git config --global user.name "Github Actions"
        git add -A 
        git commit -m "publish  $GITHUB_SHA on `date '+%F %T %Z'`"
        git push -u origin master
