name: Haskell CI

on:
  push:
    branches: [ hakyll ]
  pull_request:
    branches: [ hakyll ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        stack-version: '2.2'
    - name: Resolve/Update dependencies
      run: |
        stack setup
        stack build --dependencies-only
    - name: Build Site
      run: stack build --pedantic
    - name: Generate Static Site
      run: stack exec site build
    - name: Publish GitHub Pages
      run: |
        stack exec site build
        git checkout -b master
        cp -a _site/ .
        git add -A 
        git commit -m "test"
        git push -u origin master
